const mongoose = require('mongoose')
const requireLogin = require('../middlewares/requireLogin')
const requireCredits = require('../middlewares/requireCredits')
const Survey = mongoose.model('surveys')
const sendMail = require('../services/Mailer')
const surveyTemplate = require('../services/emailTemplates/surveyTemplate')

module.exports = app => {
    app.post('/api/surveys', requireLogin ,requireCredits , async (req, res) => {

        const { title, subject, body, recipients } = req.body;
        
        const survey = new Survey({
            title,
            subject,
            body,
            recipients : recipients.split(',').map( (email) => {return { email : email.trim() } }),
            _user : req.user.id,
            dateSent : Date.now()
        })

        try {
            await sendMail(survey)

            await survey.save();

            req.user.credits -=1 ;

            const user = await req.user.save();

            res.send(user);

        }catch(err){
            res.status(422).send(err);
        }
    });


    app.get('/api/surveys', (req, res) => {
        res.send('<h1>Hey ! Thanks for your feedback</h1>')
    })

}

/* _user denotes a relational object and id here is generated by Mongoose itself.*/